//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTypeApp.TypeRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.web.courses.org/", ConfigurationName="TypeRef.ITypeService")]
    public interface ITypeService {
        
        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestTypeApp.TypeRef.saveResponse save(TestTypeApp.TypeRef.save request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.saveResponse> saveAsync(TestTypeApp.TypeRef.save request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.TypeRef.readResponse read(TestTypeApp.TypeRef.read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readResponse> readAsync(TestTypeApp.TypeRef.read request);
        
        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestTypeApp.TypeRef.deleteResponse delete(TestTypeApp.TypeRef.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.deleteResponse> deleteAsync(TestTypeApp.TypeRef.delete request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.TypeRef.findResponse find(TestTypeApp.TypeRef.find request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.findResponse> findAsync(TestTypeApp.TypeRef.find request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.TypeRef.readAllResponse readAll(TestTypeApp.TypeRef.readAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readAllResponse> readAllAsync(TestTypeApp.TypeRef.readAll request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.web.courses.org/")]
    public partial class type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type[] arg0;
        
        public save() {
        }
        
        public save(TestTypeApp.TypeRef.type[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class saveResponse {
        
        public saveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="read", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public read() {
        }
        
        public read(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type @return;
        
        public readResponse() {
        }
        
        public readResponse(TestTypeApp.TypeRef.type @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public delete() {
        }
        
        public delete(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class deleteResponse {
        
        public deleteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class find {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public find() {
        }
        
        public find(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class findResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type[] @return;
        
        public findResponse() {
        }
        
        public findResponse(TestTypeApp.TypeRef.type[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAll", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readAll {
        
        public readAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAllResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type[] @return;
        
        public readAllResponse() {
        }
        
        public readAllResponse(TestTypeApp.TypeRef.type[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITypeServiceChannel : TestTypeApp.TypeRef.ITypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TypeServiceClient : System.ServiceModel.ClientBase<TestTypeApp.TypeRef.ITypeService>, TestTypeApp.TypeRef.ITypeService {
        
        public TypeServiceClient() {
        }
        
        public TypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.saveResponse TestTypeApp.TypeRef.ITypeService.save(TestTypeApp.TypeRef.save request) {
            return base.Channel.save(request);
        }
        
        public void save(TestTypeApp.TypeRef.type[] arg0) {
            TestTypeApp.TypeRef.save inValue = new TestTypeApp.TypeRef.save();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.saveResponse retVal = ((TestTypeApp.TypeRef.ITypeService)(this)).save(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.saveResponse> TestTypeApp.TypeRef.ITypeService.saveAsync(TestTypeApp.TypeRef.save request) {
            return base.Channel.saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.saveResponse> saveAsync(TestTypeApp.TypeRef.type[] arg0) {
            TestTypeApp.TypeRef.save inValue = new TestTypeApp.TypeRef.save();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.ITypeService)(this)).saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.readResponse TestTypeApp.TypeRef.ITypeService.read(TestTypeApp.TypeRef.read request) {
            return base.Channel.read(request);
        }
        
        public TestTypeApp.TypeRef.type read(int arg0) {
            TestTypeApp.TypeRef.read inValue = new TestTypeApp.TypeRef.read();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.readResponse retVal = ((TestTypeApp.TypeRef.ITypeService)(this)).read(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readResponse> TestTypeApp.TypeRef.ITypeService.readAsync(TestTypeApp.TypeRef.read request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.readResponse> readAsync(int arg0) {
            TestTypeApp.TypeRef.read inValue = new TestTypeApp.TypeRef.read();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.ITypeService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.deleteResponse TestTypeApp.TypeRef.ITypeService.delete(TestTypeApp.TypeRef.delete request) {
            return base.Channel.delete(request);
        }
        
        public void delete(int arg0) {
            TestTypeApp.TypeRef.delete inValue = new TestTypeApp.TypeRef.delete();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.deleteResponse retVal = ((TestTypeApp.TypeRef.ITypeService)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.deleteResponse> TestTypeApp.TypeRef.ITypeService.deleteAsync(TestTypeApp.TypeRef.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.deleteResponse> deleteAsync(int arg0) {
            TestTypeApp.TypeRef.delete inValue = new TestTypeApp.TypeRef.delete();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.ITypeService)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.findResponse TestTypeApp.TypeRef.ITypeService.find(TestTypeApp.TypeRef.find request) {
            return base.Channel.find(request);
        }
        
        public TestTypeApp.TypeRef.type[] find(string arg0) {
            TestTypeApp.TypeRef.find inValue = new TestTypeApp.TypeRef.find();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.findResponse retVal = ((TestTypeApp.TypeRef.ITypeService)(this)).find(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.findResponse> TestTypeApp.TypeRef.ITypeService.findAsync(TestTypeApp.TypeRef.find request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.findResponse> findAsync(string arg0) {
            TestTypeApp.TypeRef.find inValue = new TestTypeApp.TypeRef.find();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.ITypeService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.readAllResponse TestTypeApp.TypeRef.ITypeService.readAll(TestTypeApp.TypeRef.readAll request) {
            return base.Channel.readAll(request);
        }
        
        public TestTypeApp.TypeRef.type[] readAll() {
            TestTypeApp.TypeRef.readAll inValue = new TestTypeApp.TypeRef.readAll();
            TestTypeApp.TypeRef.readAllResponse retVal = ((TestTypeApp.TypeRef.ITypeService)(this)).readAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readAllResponse> TestTypeApp.TypeRef.ITypeService.readAllAsync(TestTypeApp.TypeRef.readAll request) {
            return base.Channel.readAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.readAllResponse> readAllAsync() {
            TestTypeApp.TypeRef.readAll inValue = new TestTypeApp.TypeRef.readAll();
            return ((TestTypeApp.TypeRef.ITypeService)(this)).readAllAsync(inValue);
        }
    }
}
